# // 🟢 workflow_main
name: Compile sing-box rule-sets 🔥

on:
  push:
    paths:
      - 'block.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install latest sing-box
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          curl -Lo sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/v${LATEST_TAG}/sing-box-${LATEST_TAG}-linux-amd64.tar.gz"
          tar -xzf sing-box.tar.gz
          mv sing-box-*/sing-box .
          chmod +x sing-box

      - name: Compile Blocklist 🛠
        run: |
          echo '{"version": 1, "rules": [{"domain": [' > block.json
          sed 's/^/"/;s/$/",/' block.txt | sed '$ s/,$//' >> block.json
          echo ']}]}' >> block.json
          
          ./sing-box rule-set compile --output block.srs block.json

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Compile geosite block.dat 📦
        run: |
          git clone --depth=1 https://github.com/v2fly/domain-list-community.git dlc
          mkdir -p dlc_data
          cp block.txt dlc_data/block
          cd dlc
          go run ./ --datapath=../dlc_data --outputname=block.dat
          mv block.dat ../block.dat
          cd ..
          rm -rf dlc dlc_data

      - name: Push results 🚀
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add block.json block.srs block.dat
          git commit -m "Update blocklists (JSON, SRS & DAT): $(date)" || exit 0
          git push
# // 🔴 workflow_main
