name: Compile sing-box rule-sets 🔥

on:
  push:
    paths:
      - 'block.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

- name: Install latest sing-box
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          curl -Lo sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/v${LATEST_TAG}/sing-box-${LATEST_TAG}-linux-amd64.tar.gz"
          tar -xzf sing-box.tar.gz
          mv sing-box-*/sing-box .
          chmod +x sing-box

      - name: Compile Blocklist 🛠
        run: |
          # Формируем JSON из block.txt
          echo '{"version": 1, "rules": [{"domain": [' > block.json
          sed 's/^/"/;s/$/",/' block.txt | sed '$ s/,$//' >> block.json
          echo ']}]}' >> block.json
          
          # Компиляция в бинарный формат .srs
          ./sing-box rule-set compile --output block.srs block.json

      - name: Push results 🚀
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add block.srs
          git commit -m "Update binary blocklist: $(date)" || exit 0
          git push
